typedef enum 
{
  UNKNOWN, 
  TEMPERATURE, 
  RELAY_ON, 
  RELAY_OFF, 
  SET_ID, 
  GET_ID, 
  GET_LOWER_TEMPERATURE_THRESHOLD, 
  GET_HIGHER_TEMPERATURE_THRESHOLD, 
  SET_LOWER_TEMPERATURE_THRESHOLD,
  SET_HIGHER_TEMPERATURE_THRESHOLD,
  SET_MODE,
  GET_MODE,
} Command;

 
